[project]
name = "h-and-m-recommendation-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "polars>=1.25.2",
]

[tool.setuptools.packages.find]
where=["resys"]
